#!/usr/bin/env python3
"""แปลง 📝 Log สต็อก (Excel) → out/import_history.sql สำหรับตาราง weekly_history
ใช้: python3 import_excel_history.py ["/path/to/Stock FullYear 2026.xlsx"]
- reconcile ชื่อกับ audit/inventory_items.json (map item_id ให้ถ้าตรง)
- idempotent: ลบ excel-import เก่าก่อน insert ใหม่
"""
import sys, json, datetime, pathlib
from openpyxl import load_workbook

HERE = pathlib.Path(__file__).parent
BRANCH_ID = 1
DEFAULT_XLSX = '/Users/faru/Desktop/stock/Stock FullYear 2026.xlsx'
MONTHS = {'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,
          'Jul':7,'Aug':8,'Sep':9,'Oct':10,'Nov':11,'Dec':12}

# แถวใน Excel ที่ไม่ใช่สินค้า (หัวหมวดแฝง/ป้ายกำกับ)
SKIP_ROWS = {'PK พาณิชย์ BKK', 'พร้อมเพย์', 'ออนไลน์', 'Supplier',
             'PK พาณิชย์ BKK ', 'ออนไลน์ '}
# ชื่อใน Excel → ชื่อใน inventory_items (เติมเมื่อเจอไม่ตรง)
NAME_MAP = {}


def load_inventory():
    data = json.load(open(HERE.parent / 'audit' / 'inventory_items.json'))
    return {x['name']: x['id'] for x in data}


def parse_week_headers(ws):
    weeks = []
    for col in range(5, ws.max_column + 1, 4):
        v = ws.cell(row=3, column=col).value
        if not v:
            continue
        parts = str(v).strip().split()          # '28 Dec 25'
        if len(parts) != 3 or parts[1] not in MONTHS:
            continue
        d = datetime.date(2000 + int(parts[2]), MONTHS[parts[1]], int(parts[0]))
        weeks.append((col, d.isoformat()))
    return weeks


def num(v):
    if v is None or str(v).strip() == '':
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def parse_items(ws, weeks):
    rows = []
    for r in range(5, ws.max_row + 1):
        raw = ws.cell(row=r, column=1).value
        if not raw:
            continue
        name = str(raw).strip()
        if name.startswith('▶') or name in SKIP_ROWS:
            continue
        unit = str(ws.cell(row=r, column=2).value or '').strip() or '-'
        for col, week in weeks:
            remaining = num(ws.cell(row=r, column=col).value)
            ordered   = num(ws.cell(row=r, column=col + 1).value)
            used      = num(ws.cell(row=r, column=col + 3).value)
            if remaining is None and ordered is None and used is None:
                continue
            rows.append({'item': NAME_MAP.get(name, name), 'unit': unit,
                         'week': week, 'remaining': remaining,
                         'ordered': ordered, 'used': used})
    return rows


def lit(s):
    return "'" + str(s).replace("'", "''") + "'"


def sqlnum(v):
    return 'null' if v is None else repr(v)


def main(path):
    ws = load_workbook(path, read_only=False, data_only=True)['📝 Log สต็อก']
    weeks = parse_week_headers(ws)
    rows = parse_items(ws, weeks)
    inv = load_inventory()

    names = sorted({r['item'] for r in rows})
    matched = [n for n in names if n in inv]
    unmatched = [n for n in names if n not in inv]

    out = HERE / 'out' / 'import_history.sql'
    out.parent.mkdir(exist_ok=True)
    with open(out, 'w') as f:
        f.write('-- generated by import_excel_history.py — idempotent\n')
        f.write('begin;\n')
        f.write("delete from public.weekly_history where source = 'excel-import';\n")
        f.write('insert into public.weekly_history '
                '(branch_id, item_id, item_name, unit, week_start_date, remaining, ordered, used, source) values\n')
        vals = []
        for r in rows:
            iid = inv.get(r['item'])
            vals.append(
                f"({BRANCH_ID}, {iid if iid else 'null'}, {lit(r['item'])}, {lit(r['unit'])}, "
                f"'{r['week']}', {sqlnum(r['remaining'])}, {sqlnum(r['ordered'])}, "
                f"{sqlnum(r['used'])}, 'excel-import')")
        f.write(',\n'.join(vals))
        f.write('\non conflict (branch_id, week_start_date, item_name, unit) do update set\n'
                '  item_id = excluded.item_id, remaining = excluded.remaining,\n'
                '  ordered = excluded.ordered, used = excluded.used, source = excluded.source;\n')
        f.write('commit;\n')

    report = HERE / 'out' / 'reconcile_report.md'
    with open(report, 'w') as f:
        f.write(f'# Reconcile Report\n\n')
        f.write(f'- อาทิตย์: {len(weeks)} ({weeks[0][1]} → {weeks[-1][1]})\n')
        f.write(f'- แถวข้อมูล: {len(rows)}\n')
        f.write(f'- สินค้าไม่ซ้ำ: {len(names)} (map item_id ได้ {len(matched)}, ไม่ตรง {len(unmatched)})\n\n')
        f.write('## ชื่อใน Excel ที่ไม่ตรง inventory_items (item_id=null แต่ยัง import ด้วย item_name)\n\n')
        for n in unmatched:
            f.write(f'- `{n}`\n')
        inv_names = set(inv)
        excel_names = set(names)
        f.write('\n## อยู่ใน inventory_items แต่ไม่มีประวัติใน Excel\n\n')
        for n in sorted(inv_names - {NAME_MAP.get(x, x) for x in excel_names}):
            f.write(f'- `{n}`\n')

    print(f'weeks: {len(weeks)} ({weeks[0][1]} → {weeks[-1][1]})')
    print(f'rows: {len(rows)}')
    print(f'items: {len(names)} (matched {len(matched)}, unmatched {len(unmatched)})')
    print(f'→ {out}')
    print(f'→ {report}')
    if unmatched:
        print('UNMATCHED:', ', '.join(unmatched))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_XLSX)
